import { DishEntity } from "@client-query/core/src/domain/entity/dish.entity";
import { DishCategory, type PrismaClient } from "@prisma/client";
import { INGREDIENTS } from "./ingredients";
import type { DishRepository } from "@client-query/core/src/infrastructure/repository/dish.repository";

export async function seedDishes(dishRepository: DishRepository) {
	await dishRepository.createMany(Object.values(DISHES));
}

export const DISHES = {
	curryRice: DishEntity.new({
		name: "カレーライス",
		price: 1000,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.water,
			INGREDIENTS.tomato,
			INGREDIENTS.onion,
			INGREDIENTS.garlic,
			INGREDIENTS.beef,
			INGREDIENTS.soySauce,
			INGREDIENTS.miso,
			INGREDIENTS.tofu,
			INGREDIENTS.carrot,
			INGREDIENTS.potato,
		],
	}),
	misoSoup: DishEntity.new({
		name: "味噌汁",
		price: 300,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.water,
			INGREDIENTS.miso,
			INGREDIENTS.tofu,
			INGREDIENTS.seaweed,
			INGREDIENTS.greenOnion,
		],
	}),
	tempuraAssortment: DishEntity.new({
		name: "天ぷら盛り合わせ",
		price: 1200,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.eggplant,
			INGREDIENTS.shrimp,
			INGREDIENTS.sweetPotato,
			INGREDIENTS.flour,
			INGREDIENTS.egg,
		],
	}),
	sushiAssortment: DishEntity.new({
		name: "寿司盛り合わせ",
		price: 2000,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.vinegar,
			INGREDIENTS.sugar,
			INGREDIENTS.salt,
			INGREDIENTS.salmon,
			INGREDIENTS.tuna,
			INGREDIENTS.shrimp,
			INGREDIENTS.egg,
			INGREDIENTS.cucumber,
			INGREDIENTS.nori,
		],
	}),
	grilledChickenSkewers: DishEntity.new({
		name: "焼き鳥",
		price: 800,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.chicken,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.sake,
			INGREDIENTS.sugar,
		],
	}),
	ramen: DishEntity.new({
		name: "ラーメン",
		price: 900,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.ramen,
			INGREDIENTS.pork,
			INGREDIENTS.egg,
			INGREDIENTS.greenOnion,
			INGREDIENTS.bambooShoot,
			INGREDIENTS.seaweed,
		],
	}),
	matchaPudding: DishEntity.new({
		name: "抹茶プリン",
		price: 500,
		category: DishCategory.DESSERT,
		ingredients: [
			INGREDIENTS.milk,
			INGREDIENTS.cream,
			INGREDIENTS.sugar,
			INGREDIENTS.greenTea,
		],
	}),
	chilledTofu: DishEntity.new({
		name: "冷奴",
		price: 400,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.tofu,
			INGREDIENTS.soySauce,
			INGREDIENTS.ginger,
			INGREDIENTS.greenOnion,
		],
	}),
	friedNoodles: DishEntity.new({
		name: "焼きそば",
		price: 800,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.soba,
			INGREDIENTS.pork,
			INGREDIENTS.cabbage,
			INGREDIENTS.carrot,
			INGREDIENTS.onion,
			INGREDIENTS.worcestershire,
		],
	}),
	okonomiyaki: DishEntity.new({
		name: "お好み焼き",
		price: 1000,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.flour,
			INGREDIENTS.egg,
			INGREDIENTS.cabbage,
			INGREDIENTS.pork,
			INGREDIENTS.mayonnaise,
			INGREDIENTS.worcestershire,
		],
	}),
	matchaLatte: DishEntity.new({
		name: "抹茶ラテ",
		price: 450,
		category: DishCategory.BEVERAGE,
		ingredients: [INGREDIENTS.greenTea, INGREDIENTS.milk, INGREDIENTS.sugar],
	}),
	eelBowl: DishEntity.new({
		name: "うな丼",
		price: 2200,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.eel,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.sugar,
		],
	}),
	octopusBalls: DishEntity.new({
		name: "たこ焼き",
		price: 600,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.flour,
			INGREDIENTS.egg,
			INGREDIENTS.octopus,
			INGREDIENTS.greenOnion,
			INGREDIENTS.ginger,
			INGREDIENTS.mayonnaise,
			INGREDIENTS.worcestershire,
		],
	}),
	porkGinger: DishEntity.new({
		name: "豚の生姜焼き",
		price: 950,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.pork,
			INGREDIENTS.ginger,
			INGREDIENTS.soySauce,
			INGREDIENTS.sake,
			INGREDIENTS.mirin,
		],
	}),
	steamedEggCustard: DishEntity.new({
		name: "茶碗蒸し",
		price: 550,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.egg,
			INGREDIENTS.chicken,
			INGREDIENTS.shrimp,
			INGREDIENTS.mushroom,
			INGREDIENTS.ginkgo,
		],
	}),
	parentAndChildBowl: DishEntity.new({
		name: "親子丼",
		price: 850,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.chicken,
			INGREDIENTS.egg,
			INGREDIENTS.onion,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
		],
	}),
	foxUdon: DishEntity.new({
		name: "きつねうどん",
		price: 750,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.udon,
			INGREDIENTS.aburaage,
			INGREDIENTS.greenOnion,
			INGREDIENTS.seaweed,
		],
	}),
	raccoonSoba: DishEntity.new({
		name: "たぬきそば",
		price: 700,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.soba,
			INGREDIENTS.tempura,
			INGREDIENTS.greenOnion,
			INGREDIENTS.seaweed,
		],
	}),
	plainSoba: DishEntity.new({
		name: "ざるそば",
		price: 800,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.soba,
			INGREDIENTS.seaweed,
			INGREDIENTS.wasabi,
			INGREDIENTS.greenOnion,
		],
	}),
	tempuraBowl: DishEntity.new({
		name: "天丼",
		price: 1100,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.shrimp,
			INGREDIENTS.eggplant,
			INGREDIENTS.sweetPotato,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
		],
	}),
	porkCutlet: DishEntity.new({
		name: "とんかつ",
		price: 1200,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.pork,
			INGREDIENTS.flour,
			INGREDIENTS.egg,
			INGREDIENTS.panko,
			INGREDIENTS.cabbage,
		],
	}),
	omeletteRice: DishEntity.new({
		name: "オムライス",
		price: 900,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.chicken,
			INGREDIENTS.egg,
			INGREDIENTS.onion,
			INGREDIENTS.ketchup,
		],
	}),
	sukiyaki: DishEntity.new({
		name: "すき焼き",
		price: 2500,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.beef,
			INGREDIENTS.tofu,
			INGREDIENTS.onion,
			INGREDIENTS.shirataki,
			INGREDIENTS.egg,
			INGREDIENTS.sugar,
			INGREDIENTS.soySauce,
		],
	}),
	shabuShabu: DishEntity.new({
		name: "しゃぶしゃぶ",
		price: 2300,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.pork,
			INGREDIENTS.cabbage,
			INGREDIENTS.onion,
			INGREDIENTS.carrot,
			INGREDIENTS.shiitake,
			INGREDIENTS.ponzu,
		],
	}),
	scatteredSushi: DishEntity.new({
		name: "ちらし寿司",
		price: 1500,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.vinegar,
			INGREDIENTS.sugar,
			INGREDIENTS.salt,
			INGREDIENTS.salmon,
			INGREDIENTS.shrimp,
			INGREDIENTS.egg,
			INGREDIENTS.cucumber,
		],
	}),
	tempuraSoba: DishEntity.new({
		name: "天ぷらそば",
		price: 1100,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.soba,
			INGREDIENTS.shrimp,
			INGREDIENTS.eggplant,
			INGREDIENTS.greenOnion,
			INGREDIENTS.seaweed,
		],
	}),
	mackerelSimmeredInMiso: DishEntity.new({
		name: "鯖の味噌煮",
		price: 950,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.mackerel,
			INGREDIENTS.miso,
			INGREDIENTS.sugar,
			INGREDIENTS.sake,
			INGREDIENTS.ginger,
		],
	}),
	chilledChineseNoodles: DishEntity.new({
		name: "冷やし中華",
		price: 850,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.ramen,
			INGREDIENTS.egg,
			INGREDIENTS.cucumber,
			INGREDIENTS.ham,
			INGREDIENTS.tomato,
			INGREDIENTS.sesameOil,
		],
	}),
	beefBowl: DishEntity.new({
		name: "牛丼",
		price: 780,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.beef,
			INGREDIENTS.onion,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.sugar,
		],
	}),
	eggplantInBroth: DishEntity.new({
		name: "茄子の揚げ浸し",
		price: 600,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.eggplant,
			INGREDIENTS.dashi,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.ginger,
		],
	}),
	seaweedSalad: DishEntity.new({
		name: "わかめサラダ",
		price: 450,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.seaweed,
			INGREDIENTS.cucumber,
			INGREDIENTS.sesameOil,
			INGREDIENTS.vinegar,
			INGREDIENTS.sugar,
		],
	}),
	porkSoup: DishEntity.new({
		name: "豚汁",
		price: 650,
		category: DishCategory.SOUP,
		ingredients: [
			INGREDIENTS.pork,
			INGREDIENTS.tofu,
			INGREDIENTS.carrot,
			INGREDIENTS.onion,
			INGREDIENTS.miso,
			INGREDIENTS.daikon,
		],
	}),
	eggSandwich: DishEntity.new({
		name: "たまごサンド",
		price: 500,
		category: DishCategory.SNACK,
		ingredients: [
			INGREDIENTS.bread,
			INGREDIENTS.egg,
			INGREDIENTS.mayonnaise,
			INGREDIENTS.salt,
		],
	}),
	friedChicken: DishEntity.new({
		name: "鶏の唐揚げ",
		price: 750,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.chicken,
			INGREDIENTS.ginger,
			INGREDIENTS.garlic,
			INGREDIENTS.soySauce,
			INGREDIENTS.sake,
			INGREDIENTS.flour,
		],
	}),
	spinachWithBonitoFlakes: DishEntity.new({
		name: "ほうれん草のお浸し",
		price: 400,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.spinach,
			INGREDIENTS.katsuobushi,
			INGREDIENTS.soySauce,
		],
	}),
	salmonRoeBowl: DishEntity.new({
		name: "いくら丼",
		price: 1800,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.salmon,
			INGREDIENTS.seaweed,
			INGREDIENTS.soySauce,
		],
	}),
	sauteedBurdockAndCarrot: DishEntity.new({
		name: "きんぴらごぼう",
		price: 450,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.burdockRoot,
			INGREDIENTS.carrot,
			INGREDIENTS.sesameOil,
			INGREDIENTS.sugar,
			INGREDIENTS.soySauce,
		],
	}),
	simmeredHijiki: DishEntity.new({
		name: "ひじきの煮物",
		price: 400,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.hijiki,
			INGREDIENTS.carrot,
			INGREDIENTS.aburaage,
			INGREDIENTS.soySauce,
			INGREDIENTS.sugar,
		],
	}),
	tofuBurger: DishEntity.new({
		name: "豆腐ハンバーグ",
		price: 900,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.tofu,
			INGREDIENTS.groundMeat,
			INGREDIENTS.onion,
			INGREDIENTS.egg,
			INGREDIENTS.panko,
			INGREDIENTS.soySauce,
		],
	}),
	simmeredPumpkin: DishEntity.new({
		name: "かぼちゃの煮物",
		price: 500,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.pumpkin,
			INGREDIENTS.dashi,
			INGREDIENTS.sugar,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
		],
	}),
	grilledMackerelWithSalt: DishEntity.new({
		name: "さばの塩焼き",
		price: 800,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.mackerel,
			INGREDIENTS.salt,
			INGREDIENTS.daikon,
			INGREDIENTS.lemon,
		],
	}),
	beefAndPotatoStew: DishEntity.new({
		name: "肉じゃが",
		price: 850,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.beef,
			INGREDIENTS.potato,
			INGREDIENTS.onion,
			INGREDIENTS.carrot,
			INGREDIENTS.soySauce,
			INGREDIENTS.sugar,
			INGREDIENTS.mirin,
		],
	}),
	chilledTofuWithToppings: DishEntity.new({
		name: "冷奴",
		price: 350,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.tofu,
			INGREDIENTS.greenOnion,
			INGREDIENTS.ginger,
			INGREDIENTS.katsuobushi,
			INGREDIENTS.soySauce,
		],
	}),
	bambooShootRice: DishEntity.new({
		name: "たけのこご飯",
		price: 700,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.bambooShoot,
			INGREDIENTS.carrot,
			INGREDIENTS.aburaage,
			INGREDIENTS.soySauce,
			INGREDIENTS.sake,
		],
	}),
	clamsSteamedInSake: DishEntity.new({
		name: "あさりの酒蒸し",
		price: 750,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.clam,
			INGREDIENTS.sake,
			INGREDIENTS.butter,
			INGREDIENTS.soySauce,
			INGREDIENTS.greenOnion,
		],
	}),
	bitterMelonStirFry: DishEntity.new({
		name: "ゴーヤチャンプルー",
		price: 800,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.bitterMelon,
			INGREDIENTS.tofu,
			INGREDIENTS.egg,
			INGREDIENTS.pork,
			INGREDIENTS.soySauce,
		],
	}),
	salmonMisoYaki: DishEntity.new({
		name: "鮭の西京焼き",
		price: 1100,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.salmon,
			INGREDIENTS.miso,
			INGREDIENTS.mirin,
			INGREDIENTS.sake,
			INGREDIENTS.sugar,
		],
	}),
	oden: DishEntity.new({
		name: "おでん",
		price: 800,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.daikon,
			INGREDIENTS.egg,
			INGREDIENTS.konjac,
			INGREDIENTS.fishCake,
			INGREDIENTS.dashi,
		],
	}),
	takikomiGohan: DishEntity.new({
		name: "炊き込みご飯",
		price: 700,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.chicken,
			INGREDIENTS.mushroom,
			INGREDIENTS.carrot,
			INGREDIENTS.soySauce,
			INGREDIENTS.sake,
		],
	}),
	takoWasabi: DishEntity.new({
		name: "たこわさ",
		price: 550,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.octopus,
			INGREDIENTS.wasabi,
			INGREDIENTS.soySauce,
		],
	}),
	mentaikoPasta: DishEntity.new({
		name: "明太子パスタ",
		price: 950,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.pasta,
			INGREDIENTS.mentaiko,
			INGREDIENTS.butter,
			INGREDIENTS.nori,
			INGREDIENTS.egg,
		],
	}),
	chaSoba: DishEntity.new({
		name: "茶そば",
		price: 850,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.greenTea,
			INGREDIENTS.soba,
			INGREDIENTS.dashi,
			INGREDIENTS.greenOnion,
			INGREDIENTS.wasabi,
		],
	}),
	buriNoTeriyaki: DishEntity.new({
		name: "ぶりの照り焼き",
		price: 1200,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.yellowtail,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.sake,
			INGREDIENTS.sugar,
			INGREDIENTS.ginger,
		],
	}),
	namekoOroshi: DishEntity.new({
		name: "なめこおろし",
		price: 400,
		category: DishCategory.SIDE_DISH,
		ingredients: [INGREDIENTS.nameko, INGREDIENTS.daikon, INGREDIENTS.soySauce],
	}),
	tororoSoba: DishEntity.new({
		name: "とろろそば",
		price: 900,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.soba,
			INGREDIENTS.yamaimo,
			INGREDIENTS.nori,
			INGREDIENTS.greenOnion,
			INGREDIENTS.quail,
		],
	}),
	yudeTamago: DishEntity.new({
		name: "ゆで卵",
		price: 200,
		category: DishCategory.SIDE_DISH,
		ingredients: [INGREDIENTS.egg, INGREDIENTS.salt],
	}),
	wasabiDon: DishEntity.new({
		name: "わさび丼",
		price: 1300,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.tuna,
			INGREDIENTS.wasabi,
			INGREDIENTS.soySauce,
			INGREDIENTS.nori,
		],
	}),
	toriSoboroDon: DishEntity.new({
		name: "鶏そぼろ丼",
		price: 850,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.chicken,
			INGREDIENTS.egg,
			INGREDIENTS.soySauce,
			INGREDIENTS.sugar,
			INGREDIENTS.mirin,
		],
	}),
	negitoroMaki: DishEntity.new({
		name: "ねぎとろ巻き",
		price: 600,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.tuna,
			INGREDIENTS.greenOnion,
			INGREDIENTS.nori,
			INGREDIENTS.whiteRice,
			INGREDIENTS.sesame,
		],
	}),
	kaniTama: DishEntity.new({
		name: "かに玉",
		price: 750,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.crab,
			INGREDIENTS.egg,
			INGREDIENTS.onion,
			INGREDIENTS.soySauce,
			INGREDIENTS.starch,
		],
	}),
	butaShabuSalad: DishEntity.new({
		name: "豚しゃぶサラダ",
		price: 900,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.pork,
			INGREDIENTS.lettuce,
			INGREDIENTS.cucumber,
			INGREDIENTS.tomato,
			INGREDIENTS.onion,
			INGREDIENTS.ponzu,
		],
	}),
	tarakoSpaghetti: DishEntity.new({
		name: "たらこスパゲッティ",
		price: 950,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.pasta,
			INGREDIENTS.mentaiko,
			INGREDIENTS.butter,
			INGREDIENTS.nori,
			INGREDIENTS.soyMilk,
		],
	}),
	hotateSashimi: DishEntity.new({
		name: "ほたて貝柱の刺身",
		price: 1200,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.scallop,
			INGREDIENTS.lemon,
			INGREDIENTS.soySauce,
			INGREDIENTS.wasabi,
		],
	}),
	taiMeshi: DishEntity.new({
		name: "鯛めし",
		price: 1500,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.whiteRice,
			INGREDIENTS.seaBream,
			INGREDIENTS.ginger,
			INGREDIENTS.soySauce,
			INGREDIENTS.sake,
			INGREDIENTS.mirin,
		],
	}),
	wakasagiTempura: DishEntity.new({
		name: "わかさぎの天ぷら",
		price: 700,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.smelt,
			INGREDIENTS.flour,
			INGREDIENTS.egg,
			INGREDIENTS.salt,
		],
	}),
	toriLiverAmakaraNi: DishEntity.new({
		name: "鶏レバーの甘辛煮",
		price: 600,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.chickenLiver,
			INGREDIENTS.soySauce,
			INGREDIENTS.sugar,
			INGREDIENTS.sake,
			INGREDIENTS.ginger,
		],
	}),
	sansaiTempura: DishEntity.new({
		name: "山菜の天ぷら",
		price: 800,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.fiddlehead,
			INGREDIENTS.butterbur,
			INGREDIENTS.flour,
			INGREDIENTS.egg,
			INGREDIENTS.tempuraSauce,
		],
	}),
	unagiKabayaki: DishEntity.new({
		name: "鰻の蒲焼",
		price: 2500,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.eel,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.sugar,
			INGREDIENTS.whiteRice,
		],
	}),
	hiyashiUdon: DishEntity.new({
		name: "冷やしうどん",
		price: 750,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.udon,
			INGREDIENTS.dashi,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.greenOnion,
		],
	}),
	sabaNoMisoNi: DishEntity.new({
		name: "鯖の味噌煮",
		price: 900,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.mackerel,
			INGREDIENTS.miso,
			INGREDIENTS.sugar,
			INGREDIENTS.sake,
			INGREDIENTS.ginger,
		],
	}),
	butaNoKakuni: DishEntity.new({
		name: "豚の角煮",
		price: 1100,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.pork,
			INGREDIENTS.soySauce,
			INGREDIENTS.sugar,
			INGREDIENTS.sake,
			INGREDIENTS.ginger,
		],
	}),
	chawanMushi: DishEntity.new({
		name: "茶碗蒸し",
		price: 600,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.egg,
			INGREDIENTS.chicken,
			INGREDIENTS.shrimp,
			INGREDIENTS.ginkgo,
			INGREDIENTS.mushroom,
		],
	}),
	gomaTofu: DishEntity.new({
		name: "ごま豆腐",
		price: 500,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.sesame,
			INGREDIENTS.kudzu,
			INGREDIENTS.dashi,
			INGREDIENTS.soySauce,
		],
	}),
	toriNoTeriyaki: DishEntity.new({
		name: "鶏の照り焼き",
		price: 850,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.chicken,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.sake,
			INGREDIENTS.sugar,
		],
	}),
	iwashiNoUmeNi: DishEntity.new({
		name: "いわしの梅煮",
		price: 700,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.sardine,
			INGREDIENTS.plum,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
		],
	}),
	zundaMochi: DishEntity.new({
		name: "ずんだもち",
		price: 400,
		category: DishCategory.DESSERT,
		ingredients: [
			INGREDIENTS.edamame,
			INGREDIENTS.sugar,
			INGREDIENTS.salt,
			INGREDIENTS.mochi,
		],
	}),
	taiNoShioyaki: DishEntity.new({
		name: "鯛の塩焼き",
		price: 1300,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.seaBream,
			INGREDIENTS.salt,
			INGREDIENTS.daikon,
			INGREDIENTS.lemon,
		],
	}),
	warabiMochi: DishEntity.new({
		name: "わらび餅",
		price: 450,
		category: DishCategory.DESSERT,
		ingredients: [
			INGREDIENTS.brackenStarch,
			INGREDIENTS.sugar,
			INGREDIENTS.soybean,
			INGREDIENTS.greenTea,
		],
	}),
	toriNoMizutaki: DishEntity.new({
		name: "鶏の水炊き",
		price: 1200,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.chicken,
			INGREDIENTS.tofu,
			INGREDIENTS.mushroom,
			INGREDIENTS.greenOnion,
			INGREDIENTS.ponzu,
		],
	}),
	horensoNoGomaAe: DishEntity.new({
		name: "ほうれん草の胡麻和え",
		price: 500,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.spinach,
			INGREDIENTS.sesame,
			INGREDIENTS.sugar,
			INGREDIENTS.soySauce,
		],
	}),
	sakeNoChanChanYaki: DishEntity.new({
		name: "鮭のちゃんちゃん焼き",
		price: 1100,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.salmon,
			INGREDIENTS.cabbage,
			INGREDIENTS.miso,
			INGREDIENTS.butter,
			INGREDIENTS.sake,
		],
	}),
	takoMeshi: DishEntity.new({
		name: "たこ飯",
		price: 900,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.octopus,
			INGREDIENTS.whiteRice,
			INGREDIENTS.soySauce,
			INGREDIENTS.mirin,
			INGREDIENTS.ginger,
		],
	}),
	kintsuba: DishEntity.new({
		name: "きんつば",
		price: 300,
		category: DishCategory.DESSERT,
		ingredients: [
			INGREDIENTS.azukiBeans,
			INGREDIENTS.sugar,
			INGREDIENTS.flour,
			INGREDIENTS.yeast,
		],
	}),
	toriNoAmazuAnkake: DishEntity.new({
		name: "鶏の甘酢あんかけ",
		price: 850,
		category: DishCategory.MAIN_COURSE,
		ingredients: [
			INGREDIENTS.chicken,
			INGREDIENTS.vinegar,
			INGREDIENTS.sugar,
			INGREDIENTS.soySauce,
			INGREDIENTS.starch,
		],
	}),
	hijikiNoNimono: DishEntity.new({
		name: "ひじきの煮物",
		price: 450,
		category: DishCategory.SIDE_DISH,
		ingredients: [
			INGREDIENTS.hijiki,
			INGREDIENTS.carrot,
			INGREDIENTS.aburaage,
			INGREDIENTS.soySauce,
			INGREDIENTS.sugar,
		],
	}),
	ajiNoNanbanzuke: DishEntity.new({
		name: "鯵の南蛮漬け",
		price: 750,
		category: DishCategory.APPETIZER,
		ingredients: [
			INGREDIENTS.horseMackerel,
			INGREDIENTS.vinegar,
			INGREDIENTS.sugar,
			INGREDIENTS.onion,
			INGREDIENTS.carrot,
		],
	}),
};
